# Generated by Django 3.0.2 on 2020-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
    ]
