# Generated by Django 3.0.2 on 2020-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_auto_20200203_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
